import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const SOURCE_PATH = "src/features/thumbnails/thumbnail-studio-panel.tsx";
const LAYOUT_SOURCE_PATH = "src/app/layout.tsx";

describe("Thumbnail Studio UI shell", () => {
    const source = readFileSync(SOURCE_PATH, "utf8");
    const layoutSource = readFileSync(LAYOUT_SOURCE_PATH, "utf8");

    it("uses a split library and editor layout with consistent app shell styling", () => {
        expect(source).toContain("xl:grid-cols-[minmax(0,3fr)_minmax(0,5fr)]");
        expect(source).toContain("xl:grid-cols-[minmax(0,3fr)_minmax(0,2fr)]");
        expect(source).toContain("Thumbnail Library");
        expect(source).toContain("Text Overlay");
        expect(source).toContain("Crop");
        expect(source).toContain("Blur");
        expect(source).toContain("aspect-video overflow-hidden border-b border-main bg-zinc-900");
        expect(source).toContain("grid auto-rows-max grid-cols-3 content-start gap-2");
        expect(source).toContain("thin-scrollbar min-h-0 flex-1 overflow-y-auto pr-1");
        expect(source).toContain("truncate px-1.5 pt-1.5 text-[11px] font-semibold text-main");
        expect(source).toContain("buildLibraryMetaLabel");
        expect(source).toContain("formatDateLabel(createdAt)");
        expect(source).toContain("formatSizeMbLabel(sizeBytes)");
        expect(source).toContain("return `${day}.${month}.${year}`;");
        expect(source).toContain("·");
        expect(source).toContain("onLoad={(event) => {");
    });

    it("supports import affordances for drag-drop and URL", () => {
        expect(source).toContain("Drag image into this box to import");
        expect(source).toContain("Import from URL");
        expect(source).toContain("handleDropUpload");
        expect(source).toContain("handleImportFromUrl");
        expect(source).toContain("if (event.key === \"Enter\")");
        expect(source).toContain("title: importUrl.trim()");
        expect(source).toContain("buildUploadTitleWithTime()");
        expect(source).not.toContain("title: file.name.replace");
    });

    it("keeps lifecycle tags and non-destructive edit defaults visible", () => {
        expect(source).toContain('"raw" | "processed" | "has-processed-output"');
        expect(source).toContain("AssetLifecycleBadges");
        expect(source).toContain("Create variant (default)");
        expect(source).toContain("Overwrite current");
        expect(source).toContain("Toggle lifecycle filter menu");
        expect(source).not.toContain("Active filter:");
    });

    it("includes rename, duplicate/delete controls, and storage-backed workflow integration", () => {
        expect(source).not.toContain("const [blurEnabled, setBlurEnabled] = useState(false);");
        expect(source).toContain("Thumbnail name");
        expect(source).toContain("Save");
        expect(source).toContain("Duplicate");
        expect(source).toContain("Reset");
        expect(source).toContain("Delete");
        expect(source).toContain("handleDuplicateSelected");
        expect(source).toContain("handleDeleteSelected");
        expect(source).toContain("handleResetEditor");
        expect(source).toContain("/api/storage/thumbnail-assets");
        expect(source).toContain("/api/storage/providers");
        expect(source).toContain("storageProviderAccountId");
        expect(source).toContain("uploadThumbnailFile");
        expect(source).toContain("renderThumbnailBlob");
        expect(source).toContain("cropSelection");
        expect(source).toContain("getOutputSizeForCrop");
        expect(source).toContain("outputContext.drawImage(");
        expect(source).not.toContain("thumbnailSetupJson");
        expect(source).not.toContain("thumbnailStudioSetup");
        expect(source).toContain("handleInlineTitleRename");
        expect(source).toContain("onDoubleClick");
        expect(source).toContain("Thumbnail name updated.");
        expect(source).not.toContain('aria-label="Duplicate thumbnail"');
        expect(source).not.toContain('aria-label="Delete thumbnail"');
        expect(source).toContain("flex h-fit w-full flex-col border text-left");
        expect(source).not.toContain("w-full border p-2 text-left");
        expect(source).not.toContain("Updated 12m ago");
        expect(source).not.toContain("Rename freely for better search and pipeline mapping.");
        expect(source).not.toContain("Workflow Output Hook");
        expect(source).not.toContain("workflow.thumbnail.select");
        expect(source).not.toContain("Publish node target");
    });

    it("uses compact multi-item blur/text summaries and drag-to-position text", () => {
        expect(source).toContain("PRESET_CROP_OPTIONS");
        expect(source).toContain("{ value: \"none\", label: \"None\" }");
        expect(source).toContain("{ value: \"custom\", label: \"Custom\" }");
        expect(source).toContain("applyCropPreset(");
        expect(source).toContain("option.value");
        expect(source).toContain("Crop selection");
        expect(source).toContain("cropPreset !== \"none\"");
        expect(source).toContain("const [cropPreset, setCropPreset] = useState<ThumbnailCropPreset>(\"none\");");
        expect(source).toContain("border-2 border-emerald-400");
        expect(source).toContain("CROP_RESIZE_HANDLES");
        expect(source).toContain("startCropInteraction");
        expect(source).toContain("handleCropPointerMove");
        expect(source).toContain("const DEFAULT_BLUR_REGIONS: BlurRegionDraft[] = [];");
        expect(source).toContain("const DEFAULT_TEXT_OVERLAYS: TextOverlayDraft[] = [];");
        expect(source).toContain("formatBlurRegionSummary");
        expect(source).toContain("formatTextOverlaySummary");
        expect(source).not.toContain("t:${region.start}s-${region.end}s");
        expect(source).toContain("function getBlurPixelsFromStrength(strength: number)");
        expect(source).toContain("if (normalizedStrength <= 0) return 0;");
        expect(source).toContain("const blurPixels = getBlurPixelsFromStrength(region.strength);");
        expect(source).toContain("if (blurPixels <= 0) continue;");
        expect(source).not.toContain("Math.max(2, Math.round(region.strength / 2.5))");
        expect(source).toContain("const samplePadding = Math.max(4, Math.ceil(blurPixels * 2));");
        expect(source).toContain("context.beginPath();");
        expect(source).toContain("context.clip();");
        expect(source).not.toContain("context.clearRect(regionX, regionY, regionWidth, regionHeight);");
        expect(source).toContain("THUMBNAIL_TEXT_FONT_OPTIONS");
        expect(source).toContain("Bangers");
        expect(source).toContain("Barlow Condensed");
        expect(source).toContain("Be Vietnam Pro");
        expect(source).toContain("Paytone One");
        expect(source).toContain("Lobster");
        expect(source).toContain("Pacifico");
        expect(source).toContain("Sriracha");
        expect(source).toContain("getThumbnailTextPreviewFontFamily");
        expect(source).toContain("getThumbnailTextCanvasFontFamily");
        expect(source).toContain("buildTextGlowCss");
        expect(source).toContain("shadowEnabled");
        expect(source).toContain("shadowColor");
        expect(source).toContain("shadowBlur");
        expect(source).toContain("shadowSpread");
        expect(source).toContain("Glow behind text");
        expect(source).toContain("Glow color");
        expect(source).toContain("Glow blur");
        expect(source).toContain("Glow spread");
        expect(source).toContain("context.shadowColor");
        expect(source).toContain("context.shadowBlur");
        expect(source).toContain("context.save();");
        expect(source).toContain("context.strokeText(line, x, lineY);");
        expect(source).toContain("!activeTextOverlay.shadowEnabled");
        expect(source).toContain("document.fonts.load");
        expect(source).toContain("const [previewFrameHeight, setPreviewFrameHeight]");
        expect(source).toContain("const previewTextScale = Math.max(");
        expect(source).toContain("overlay.fontSize *");
        expect(source).toContain("selectAssetIdAfterUpload");
        expect(source).toContain("const sourceThumbnailId = selectedThumbnailId;");
        expect(source).toContain("editMode === \"create-variant\"");
        expect(layoutSource).toContain("Montserrat({");
        expect(layoutSource).toContain("Oswald({");
        expect(layoutSource).toContain("Bebas_Neue");
        expect(layoutSource).toContain("Anton({");
        expect(layoutSource).toContain("Bangers({");
        expect(layoutSource).toContain("Barlow_Condensed");
        expect(layoutSource).toContain("Paytone_One");
        expect(layoutSource).toContain("Pacifico({");
        expect(layoutSource).toContain("Sriracha({");
        expect(layoutSource).toContain("--font-thumb-montserrat");
        expect(layoutSource).toContain("--font-thumb-bebas-neue");
        expect(layoutSource).toContain("--font-thumb-bangers");
        expect(layoutSource).toContain("--font-thumb-pacifico");
        expect(source).toContain("Add blur region");
        expect(source).toContain("Add text layer");
        expect(source).toContain("min-w-0 max-w-full flex-1 truncate whitespace-nowrap text-left text-[10px]");
        expect(source).toContain("flex w-full max-w-full items-center gap-1 overflow-hidden border px-1.5 py-1");
        expect(source).toContain("Remove blur region #");
        expect(source).toContain("Remove text layer #");
        expect(source).toContain("<X className=\"h-3 w-3\" />");
        expect(source).toContain("startBlurInteraction");
        expect(source).toContain("Resize blur region");
        expect(source).toContain("BLUR_RESIZE_HANDLES");
        expect(source).toContain("<Droplets className=\"h-4 w-4 text-muted\" />");
        expect(source).toContain("className=\"absolute cursor-move border border-main\"");
        expect(source).toContain("WebkitBackdropFilter");
        expect(source).not.toContain("bg-black/40");
        expect(source).not.toContain("<Filter className=\"h-4 w-4 text-muted\" />");
        expect(source).not.toContain("border-white/70");
        expect(source).toContain("absolute z-10 bg-transparent");
        expect(source).not.toContain("rounded-full bg-accent");
        expect(source).not.toContain("Remove active blur region");
        expect(source).not.toContain("Remove active text layer");
        expect(source).not.toContain("X %");
        expect(source).not.toContain("Y %");
        expect(source).not.toContain("Width %");
        expect(source).not.toContain("Height %");
        expect(source).not.toContain("Start (s)");
        expect(source).not.toContain("End (s)");
        expect(source).not.toContain("Region blur");
        expect(source).not.toContain("Blur logos/faces by region.");
        expect(source).toContain("Text position: drag directly on preview");
        expect(source).toContain("onPointerDown");
        expect(source).toContain("onPointerMove");
        expect(source).toContain("const [textDragState, setTextDragState]");
        expect(source).toContain("offsetXPercent");
        expect(source).toContain("offsetYPercent");
        expect(source).toContain("handleCanvasTextDrag(");
        expect(source).toContain("Drag text overlay on preview #");
        expect(source).not.toContain("Drag blur block to move.");
        expect(source).not.toContain("Text X position");
        expect(source).not.toContain("Text Y position");
    });
});
